spring:
  data source:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?enabledTLSProtocols=TLSv1.2&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true  
spring-doc:
  pathsToMatch: /api/**/v1/**      
  swagger-ui:
    use-root-path: true            